import { icon, REPO, pageIntro, finalCta } from './site-ui.mjs';
import { downloadSection, mcpSpotlight } from './sections.mjs';

const actions = '<a class="button button-primary" href="download.html">Download Canopod</a><a class="button button-secondary" href="getting-started.html">Read the docs</a>';
const faq = (items) => `<div class="faq-list">${items.map(([q,a])=>`<details><summary>${q}${icon('plus')}</summary><p>${a}</p></details>`).join('')}</div>`;
const step = (number,title,body) => `<article><span class="step-number">${number}</span><h3>${title}</h3><p>${body}</p></article>`;

function features() {
  return pageIntro({eyebrow:'THE CANOPOD WORKSPACE',title:'All the moving parts.<br><em>One place to manage them.</em>',description:'Git worktrees are the starting point. Canopod brings the setup, services, terminals, and agent context together so you can actually work in them.',actions}) + `
  <section class="feature-index container" aria-label="Product capabilities"><a href="#worktrees">Worktrees</a><a href="#services">Services & ports</a><a href="#databases">Postgres</a><a href="#agents">Agents & MCP</a><a href="#setup">Repeatable setup</a></section>
  <section class="feature-detail container" id="worktrees"><div><p class="eyebrow">01 / GIT WORKTREES</p><h2>Leave your work<br>right where it is.</h2><p>Check out another branch in its own folder. Canopod finds existing worktrees and helps you create new ones from a branch or tag, so you can run a review, a feature, and a hotfix side by side.</p><ul class="plain-checks"><li>Discover worktrees you created outside Canopod.</li><li>Create worktrees and initialize submodules.</li><li>Run the setup your repository defines.</li></ul><a class="text-link" href="worktrees.html">Read the worktree guide</a></div><figure class="detail-shot"><img src="assets/screens/dark/modal-new-worktree.png" width="2800" height="1640" loading="lazy" alt="The real Canopod New worktree dialog, with branch and base selection."><figcaption>Create a worktree from a branch or tag.</figcaption></figure></section>
  <section class="feature-detail container reverse" id="services"><div><p class="eyebrow">02 / SERVICES & PORTS</p><h2>Know what’s running.<br>Know where to find it.</h2><p>Keep the frontend, API, and other configured services with their worktree. Start or stop them, open their local URLs, and read their output in a shared log stream.</p><ul class="plain-checks"><li>Stable port offsets for each worktree.</li><li>Per-service port overrides when you need them.</li><li>Logs and terminal sessions in the same window.</li></ul><p class="detail-note">Another repository or process can still use the same port. Canopod makes your assignments visible and editable.</p><a class="text-link" href="services-ports.html">Explore services and ports</a></div><figure class="detail-shot"><img src="assets/screens/dark/main-worktree.png" width="2800" height="1640" loading="lazy" alt="Service ports and combined frontend and server logs in Canopod."><figcaption>Your branch’s services, ports, and logs together.</figcaption></figure></section>
  <section class="feature-detail container" id="databases"><div><p class="eyebrow">03 / POSTGRES WORKFLOWS</p><h2>Try the migration.<br>Keep a way back.</h2><p>Configure a Postgres database for each worktree, then snapshot or restore it as you work. Branch-specific data is especially useful when two branches expect different schemas.</p><ul class="plain-checks"><li>Snapshot, export, restore, and switch databases.</li><li>Run your configured migration and reset commands.</li><li>Keep your main branch’s data separate from experiments.</li></ul><p class="detail-note">Database tools need local Postgres and compatible client binaries. Other databases can run as services.</p><a class="text-link" href="databases.html">See the database workflow</a></div><figure class="detail-shot"><img src="assets/screens/dark/modal-database.png" width="2800" height="1640" loading="lazy" alt="Canopod database actions for the selected worktree."><figcaption>Database actions stay with the worktree you selected.</figcaption></figure></section>
  <section class="capability-section container" id="agents"><div class="section-heading"><p class="eyebrow">04 / WORKING WITH AGENTS</p><h2>Two ways to bring<br>your agent into the workflow.</h2></div><div class="capability-grid two-up"><article>${icon('terminal')}<h3>Launch with context.</h3><p>Start a configured CLI such as Claude Code, Codex, or Aider inside a worktree. Canopod writes your task, branch, ports, and database to a handoff file.</p><a class="text-link" href="agents-terminals.html">Terminal sessions & handoffs</a></article><article>${icon('layers')}<h3>Connect through MCP.</h3><p>Let a local MCP client ask Canopod about the workspace and use the operations you enable. Share selected repositories and start with read-only access.</p><a class="text-link" href="canopod-mcp.html">Explore Canopod MCP</a></article></div></section>
  <section class="config-section container" id="setup"><div><p class="eyebrow">05 / REPEATABLE SETUP</p><h2>Put the setup<br>in the repository.</h2><p>A committed <code>.worktreemanager.json</code> records the files, commands, and environment overrides each worktree needs. The next branch can use that same recipe.</p><a class="text-link" href="config-worktreemanager.html">Configuration reference</a></div><div class="setup-recipe"><div>${icon('branch')} New worktree</div><ol><li><span>01</span> Seed the configured files</li><li><span>02</span> Apply environment overrides</li><li><span>03</span> Install dependencies</li><li><span>04</span> Run configured setup & migrations</li></ol><p>You define the commands. Canopod runs the recipe.</p></div></section>
  <section class="compatibility container"><div><h2>Keep the stack you use.</h2><p>Canopod detects Node services from <code>package.json</code>. For other stacks, provide the commands your project needs.</p></div><div class="stack-list"><span>Node.js</span><span>Rails</span><span>Django</span><span>Go</span><span>Rust</span></div><a class="text-link" href="example-other-stacks.html">See configuration examples</a></section>` + finalCta();
}

function mcpPage() {
  return pageIntro({eyebrow:'CANOPOD MCP / MODEL CONTEXT PROTOCOL',title:'Your agent writes the code.<br><em>Give it the workspace, too.</em>',description:'Canopod MCP connects your coding agent to your local worktrees, services, and setup jobs. It can find out what’s running and help prepare a branch, without you relaying every detail.',actions:'<a class="button button-primary" href="download.html">Get Canopod with MCP</a><a class="button button-secondary" href="#connect">Connect your agent</a>'}) + `
  <div class="mcp-facts container"><span>15 tools in v0.5</span><span>Local Streamable HTTP</span><span>Read-only access available</span><span>Off until you enable it</span></div>
  <section class="mcp-demo-section container" aria-labelledby="mcp-example-title"><div class="section-heading"><p class="eyebrow">WHAT YOU CAN ASK</p><h2 id="mcp-example-title">Let the agent ask Canopod.</h2><p>These examples show how a request maps to Canopod’s tools.<br>They’re illustrations of the workflow, not a live connection.</p></div><div class="mcp-demo"><div class="scenario-tabs" data-tabset role="tablist" aria-label="MCP workflow examples"><button role="tab" id="scenario-inspect" aria-controls="scenario-panel-inspect" aria-selected="true">Understand the workspace</button><button role="tab" id="scenario-setup" aria-controls="scenario-panel-setup" aria-selected="false" tabindex="-1">Prepare a branch</button><button role="tab" id="scenario-services" aria-controls="scenario-panel-services" aria-selected="false" tabindex="-1">Check a service</button></div>
  <div role="tabpanel" id="scenario-panel-inspect" aria-labelledby="scenario-inspect" tabindex="0" class="scenario-panel"><div class="example-request"><span class="eyebrow">YOU ASK</span><p>“Which worktrees are running in the repositories I’ve shared with Canopod?”</p><span class="permission-label">Read access</span></div><ol class="tool-trace"><li><code>canopod_repositories</code><span>Find the repositories you’ve allowed.</span></li><li><code>canopod_worktrees</code><span>List their worktrees and branches.</span></li><li><code>canopod_services</code><span>Read the reported service states.</span></li></ol></div>
  <div role="tabpanel" id="scenario-panel-setup" aria-labelledby="scenario-setup" tabindex="0" class="scenario-panel" hidden><div class="example-request"><span class="eyebrow">YOU ASK</span><p>“In my selected repository, create a worktree for feat/search from main and follow its configured setup.”</p><span class="permission-label">Worktree creation & setup permission</span></div><ol class="tool-trace"><li><code>canopod_create_worktree</code><span>Create the named branch’s worktree using repository defaults.</span></li><li><code>canopod_job</code><span>Wait for creation and any provisioning to finish.</span></li><li><code>canopod_run_setup</code><span>If setup was skipped, run it and follow its job to completion.</span></li><li><code>canopod_job_output</code><span>Read the setup output and report any failure.</span></li></ol></div>
  <div role="tabpanel" id="scenario-panel-services" aria-labelledby="scenario-services" tabindex="0" class="scenario-panel" hidden><div class="example-request"><span class="eyebrow">YOU ASK</span><p>“Check the API service in my selected worktree. Show me its recent logs, then restart it.”</p><span class="permission-label">Read + service-control permission</span></div><ol class="tool-trace"><li><code>canopod_services</code><span>Find the configured service and its state.</span></li><li><code>canopod_service_logs</code><span>Read recent, bounded service logs.</span></li><li><code>canopod_restart_service</code><span>Restart it, then follow the returned job.</span></li></ol></div>
  <div class="example-footnote">“Selected” means identified in your conversation with the agent; MCP does not inherit the desktop selection. The agent needs the repository and worktree IDs. A running process still needs a readiness check.</div></div></section>
  <section class="capability-section container"><div class="section-heading split-heading"><div><p class="eyebrow">THE TOOLS, IN PLAIN ENGLISH</p><h2>A useful set of operations.<br>Access you can choose.</h2></div><a class="text-link" href="mcp.html">Read the technical guide</a></div><div class="capability-grid"><article>${icon('layers')}<span class="capability-count">9 READ TOOLS</span><h3>Get the current picture.</h3><p>Discover allowed repositories, inspect worktrees and setup state, read service status, follow jobs, and look at recent logs or supported configuration.</p></article><article>${icon('branch')}<span class="capability-count">2 SETUP TOOLS</span><h3>Prepare the next branch.</h3><p>Create a worktree for a named branch and run your configured setup. Follow the job’s output instead of copying it from another terminal.</p></article><article>${icon('terminal')}<span class="capability-count">3 SERVICE TOOLS</span><h3>Manage what’s running.</h3><p>Start, stop, or restart configured services in the selected worktree. Keep your agent and the desktop app working from the same backend.</p></article><article>${icon('code')}<span class="capability-count">1 CONFIGURATION TOOL</span><h3>Adjust supported settings.</h3><p>Update supported repository fields or existing service settings with revision checks. This permission is separate from setup and service control.</p></article></div></section>
  <section class="mcp-connect-section" id="connect"><div class="container"><div class="section-heading"><p class="eyebrow">CONNECT YOUR AGENT</p><h2>A few choices in Settings.<br>Then back to your editor.</h2><p>First, add your repository to Canopod. Then open <strong>Settings → MCP</strong>.</p></div><div class="workflow-grid">${step('01','Choose the repositories.','Select the repositories the agent can access. Leave everything else outside its scope.')}${step('02','Choose its permissions.','Start read-only. Enable worktree setup, service control, or configuration when the task needs them, then select Enable MCP.')}${step('03','Connect your client.','Choose Claude Code or Codex under Connect to agent, connect it, and restart or reconnect the client.')}</div><div class="client-setup"><div class="client-tabs" data-tabset role="tablist" aria-label="MCP client setup"><button id="client-claude" role="tab" aria-controls="client-panel-claude" aria-selected="true">Claude Code</button><button id="client-codex" role="tab" aria-controls="client-panel-codex" aria-selected="false" tabindex="-1">Codex</button><button id="client-other" role="tab" aria-controls="client-panel-other" aria-selected="false" tabindex="-1">Other MCP clients</button></div><div class="client-panel" role="tabpanel" id="client-panel-claude" aria-labelledby="client-claude" tabindex="0"><h3>Connect Claude Code from Canopod.</h3><p>In Settings → MCP, select Claude Code and click <strong>Connect Claude Code</strong>. Restart or reconnect Claude Code, then use the first task Canopod provides to check the connection.</p><p class="detail-note">Use a current client. If you use a custom CLAUDE_CONFIG_DIR, follow the manual connection instructions.</p></div><div class="client-panel" role="tabpanel" id="client-panel-codex" aria-labelledby="client-codex" tabindex="0" hidden><h3>Connect Codex from Canopod.</h3><p>In Settings → MCP, select Codex and click <strong>Connect Codex</strong>. Restart or reconnect Codex so it loads the connection, then try the first task shown in Canopod.</p><p class="detail-note">Automatic setup preserves the client’s other settings. Use a current Codex installation.</p></div><div class="client-panel" role="tabpanel" id="client-panel-other" aria-labelledby="client-other" tabindex="0" hidden><h3>Use a compatible local MCP client.</h3><p>Open the manual setup instructions in Settings → MCP. Use the local Streamable HTTP endpoint and bearer authorization Canopod shows there. Keep that token private.</p><p class="detail-note">Remote exposure is unsupported. Client-specific setup varies; use the instructions for your MCP client.</p></div></div></div></section>
  <section class="boundaries-section container"><div><p class="eyebrow">A CLEAR SCOPE</p><h2>You choose what<br>the agent can reach.</h2><p>MCP is off by default and only listens locally. Repositories and capabilities are explicit choices in Settings.</p><a class="text-link" href="security.html">How Canopod handles access</a></div><div class="boundary-list"><div><h3>Configured operations</h3><p>Setup and service commands run from your configuration. There is no general-purpose shell tool. Review the commands and grants you enable.</p></div><div><h3>Deliberate limits in v0.5</h3><p>Dedicated worktree-removal and database-management tools aren’t exposed through MCP. Configuration patches cover supported fields, not adding or removing services.</p></div><div><h3>Local connection, your client’s data policy</h3><p>Canopod sends no telemetry. Your coding agent may send workspace context to its provider according to that client’s settings.</p></div></div></section>
  <section class="mcp-questions container"><div class="section-heading"><h2>A few details worth knowing.</h2></div>${faq([
    ['Is MCP the same as launching an agent in a terminal?','They are separate features. A terminal agent gets a task handoff and runs in a worktree. An MCP client calls the tools Canopod exposes, using the repositories and permissions you have allowed. You can use either workflow.'],
    ['Can I run the MCP backend without the desktop app?','Yes. The packaged <code>canopod-backend serve</code> runs headlessly under your own process supervisor. In v0.5, it cannot own the same data directories at the same time as the desktop app. <a href="mcp.html#headless-setup">Read the headless setup guide.</a>'],
    ['Does my agent get the full log history?','No. Service logs are bounded and read tools can use cached state. Use the reported state and recent output as evidence, and perform a readiness check before treating a service as ready.'],
    ['Where can I see all of the tool names?','The <a href="mcp.html#tool-reference">MCP tool reference</a> lists the 15 tools and their required permissions. You can also inspect the implementation in the open-source repository.']
  ])}</section>` + finalCta({title:'Give your agent a better starting point.',description:'Install Canopod, add a repository, and connect your agent when you’re ready.'});
}

function workflows() {
  return pageIntro({eyebrow:'EVERYDAY DEVELOPMENT, WITH FEWER DETOURS',title:'Your work has branches.<br><em>Your workspace should, too.</em>',description:'A review arrives halfway through a feature. A hotfix interrupts a migration. An agent needs a clean place to work. Keep those tasks separate without losing track of them.',actions}) + `
  <nav class="feature-index container" aria-label="Workflows"><a href="#review">Review a PR</a><a href="#hotfix">Handle a hotfix</a><a href="#agents">Work with agents</a><a href="#migrations">Test a migration</a></nav>
  <section class="workflow-story container" id="review"><div class="story-heading"><span class="story-index">01</span><p class="eyebrow">PR REVIEWS</p><h2>Run the review.<br>Leave your feature alone.</h2><p>Reading the diff is one thing. Running the change is another. Give the review branch its own worktree so you can try it without taking over your current checkout.</p></div><div class="story-recipe"><h3>A practical review loop</h3><ol><li>Fetch the review branch into your local repository.</li><li>Create a worktree from that branch in Canopod.</li><li>Run its configured setup and start its services.</li><li>Open its local port and try the behavior you’re reviewing.</li></ol><p>Your feature can stay checked out and running in its own worktree.</p><a class="text-link" href="first-worktree.html">Create your first worktree</a></div></section>
  <section class="workflow-story container" id="hotfix"><div class="story-heading"><span class="story-index">02</span><p class="eyebrow">HOTFIXES</p><h2>The urgent fix<br>gets its own space.</h2><p>You shouldn’t need to tidy up half-written code just to investigate a bug. Start a separate worktree from the right base and return to your feature when the fix is done.</p></div><div class="story-recipe"><h3>Keep the interruption contained</h3><ol><li>Choose the base branch or tag for the fix.</li><li>Create a named hotfix worktree and run its setup.</li><li>Start its services with the assigned ports.</li><li>Make and verify the fix, then return to your original worktree.</li></ol><p>Canopod manages the environment. Keep using your usual Git and review workflow to ship the change.</p><a class="text-link" href="worktrees.html">Managing branches and worktrees</a></div></section>
  <section class="workflow-story container" id="agents"><div class="story-heading"><span class="story-index">03</span><p class="eyebrow">CODING AGENTS</p><h2>Give each task<br>the right context.</h2><p>An agent needs more than a branch name. Give it a task, the correct worktree, and the runtime details that go with it. Keep separate tasks from sharing the same checkout.</p></div><div class="story-recipe"><h3>Work alongside your agent</h3><ol><li>Create a worktree for the task you want to delegate.</li><li>Add the brief and useful references to its context.</li><li>Launch your configured coding-agent CLI in that worktree.</li><li>Use Canopod MCP when the agent needs to inspect or manage the workspace.</li></ol><p>You can read service logs beside the agent session and keep another branch open for your own work.</p><a class="text-link" href="canopod-mcp.html">Connect your agent with MCP</a></div></section>
  <section class="workflow-story container" id="migrations"><div class="story-heading"><span class="story-index">04</span><p class="eyebrow">DATABASE CHANGES</p><h2>Test the schema<br>without sharing the fallout.</h2><p>Two branches may expect different database schemas. Configure an independent Postgres database per worktree and keep a snapshot before trying a migration.</p></div><div class="story-recipe"><h3>Make the experiment repeatable</h3><ol><li>Configure a worktree-specific database and connection settings.</li><li>Take a snapshot of the data you want to preserve.</li><li>Run the branch’s configured migration and test the change.</li><li>Restore the snapshot when you need a clean retry.</li></ol><p>These tools require local Postgres and client binaries that match the server’s major version.</p><a class="text-link" href="databases.html">Snapshot and restore a database</a></div></section>` + finalCta({title:'Start with the branch you’re on.',description:'Add your repository today. Make room for the next task when it arrives.'});
}

function downloads(version) {
  return pageIntro({eyebrow:`DOWNLOAD CANOPOD / VERSION ${version}`,title:'Ready when<br> <em>your next branch is.</em>',description:'Free, open source, and yours to run locally. Start with the desktop app, then connect a coding agent through MCP whenever it helps.'}) + downloadSection(version) + `
  <section class="download-requirements container"><div class="section-heading"><h2>A few things to have ready.</h2><p>Canopod manages your project’s tools. It doesn’t replace them.</p></div><div class="requirements-grid"><div>${icon('branch')}<h3>Git and your project’s runtimes</h3><p>Install Git and the package managers or runtimes your configured commands use. Canopod itself doesn’t require Node.</p></div><div>${icon('database')}<h3>Postgres, when you need it</h3><p>A local database is optional. Snapshot, restore, and other database workflows require Postgres and compatible client binaries.</p></div><div>${icon('terminal')}<h3>Your agent, if you use one</h3><p>For MCP, use a current Claude Code or Codex installation, or another compatible local MCP client. Enable access in Canopod Settings.</p></div></div></section>
  <section class="download-help container"><div><h2>Installed? Look in your menu bar.</h2><p>Open Canopod, add a repository, and review the detected setup. The tray icon is your shortcut back to your workspaces.</p><a class="text-link" href="onboarding.html">Add your first repository</a></div><div><h2>Need a hand?</h2><p>The docs cover platform requirements, first-launch prompts, and common setup problems.</p><a class="text-link" href="troubleshooting.html">Troubleshooting</a><a class="text-link" href="${REPO}/issues">Report an issue</a></div></section>`;
}

export function marketingPages(version) {
  return [
    {slug:'features',title:'Canopod features — Worktrees, services, databases & agents',description:'Explore Canopod’s Git worktree management, stable service ports, Postgres tools, terminals, agent handoffs and local MCP integration.',body:features()},
    {slug:'canopod-mcp',title:'Canopod MCP — Connect Claude Code & Codex to your worktrees',description:'Connect local coding agents to Canopod with 15 MCP tools for worktree context, configured setup, services and supported configuration. Choose repositories and permissions.',body:mcpPage()},
    {slug:'workflows',title:'Canopod workflows — PR reviews, hotfixes & coding agents',description:'Keep PR reviews, hotfixes, agent tasks and database experiments in separate Git worktrees with Canopod. Practical workflows and setup guides.',body:workflows()},
    {slug:'download',title:'Download Canopod — macOS, Linux & Windows',description:`Download Canopod ${version} for macOS on Apple Silicon. Get experimental Linux and Windows packages, Homebrew installation, requirements and first-launch help.`,body:downloads(version)},
  ];
}
