import { REPO, BREW, icon, mark, downloadButton } from "./site-ui.mjs";

export function downloadSection(version) {
  const release = `${REPO}/releases/download/v${version}`;
  const dmg = `${release}/Canopod_${version}_aarch64.dmg`;
  return `  <section class="download-section section-pad container" id="download" aria-labelledby="download-title">
    <div class="download-intro"><div class="download-mark">${mark}</div><p class="eyebrow">MAKE ROOM FOR YOUR NEXT IDEA</p><h2 id="download-title">Keep your flow.<br><em>Get Canopod.</em></h2><p>Your machine. Your branches. A little less friction.</p><div class="download-facts"><span>${icon("check")} Free & open source</span><span>${icon("check")} No account needed</span><span>${icon("check")} No telemetry</span></div></div>
    <div class="download-box">
      <div class="platform-tabs" role="tablist" aria-label="Download platform"><button id="tab-macos" role="tab" aria-selected="true" aria-controls="panel-macos" data-platform="macos">macOS</button><button id="tab-linux" role="tab" aria-selected="false" aria-controls="panel-linux" tabindex="-1" data-platform="linux">Linux</button><button id="tab-windows" role="tab" aria-selected="false" aria-controls="panel-windows" tabindex="-1" data-platform="windows">Windows</button></div>
      <div id="panel-macos" class="platform-panel" role="tabpanel" aria-labelledby="tab-macos" tabindex="0"><div class="platform-heading"><h3>At home in your menu bar.</h3><span>v${version}</span></div><p>For macOS on Apple Silicon (M1 and later).</p>${downloadButton(dmg, "Download for macOS", "button-wide")}<div class="or-divider"><span>OR INSTALL WITH HOMEBREW</span></div><div class="copy-command"><code id="brew-command">${BREW}</code><button type="button" data-copy="${BREW}" aria-label="Copy Homebrew install command">${icon("copy")}</button></div><p class="install-note">Homebrew is recommended. Installing the DMG? Canopod isn’t notarized yet. <a href="install-macos.html">Follow the first-launch steps.</a></p></div>
      <div id="panel-linux" class="platform-panel" role="tabpanel" aria-labelledby="tab-linux" tabindex="0" hidden><div class="platform-heading"><h3>For your Linux desktop.</h3><span class="experimental">Experimental</span></div><p>64-bit x86 packages. Choose your preferred format.</p><div class="linux-downloads">${downloadButton(`${release}/Canopod_${version}_amd64.AppImage`, "AppImage")}${downloadButton(`${release}/Canopod_${version}_amd64.deb`, ".deb")}${downloadButton(`${release}/Canopod-${version}-1.x86_64.rpm`, ".rpm")}</div><p class="install-note">Linux packages build in CI but haven’t been validated on a desktop. <a href="install-linux.html">Read the Linux install guide.</a></p><a class="text-link" href="${REPO}/issues">Share feedback on GitHub</a></div>
      <div id="panel-windows" class="platform-panel" role="tabpanel" aria-labelledby="tab-windows" tabindex="0" hidden><div class="platform-heading"><h3>A place in your system tray.</h3><span class="experimental">Experimental</span></div><p>Windows x64 installer.</p>${downloadButton(`${release}/Canopod_${version}_x64-setup.exe`, "Download for Windows", "button-wide")}<p class="install-note">Windows builds haven’t been validated on a desktop. The installer isn’t code-signed yet, so SmartScreen may show a warning. <a href="install-windows.html">Read the Windows install guide.</a></p><a class="text-link" href="${REPO}/issues">Share feedback on GitHub</a></div>
      <div class="download-box-footer"><a href="${REPO}/releases">All releases</a><span>Made with Tauri + Rust</span></div>
    </div><span class="sr-only" id="copy-status" role="status" aria-live="polite"></span>
  </section>`;
}

export function mcpSpotlight() {
  return `<section class="mcp-spotlight" aria-labelledby="mcp-spotlight-title"><div class="container mcp-spotlight-grid"><div class="mcp-spotlight-copy"><p class="eyebrow">INTRODUCING CANOPOD MCP</p><h2 id="mcp-spotlight-title">Your agent can help<br><em>with the setup, too.</em></h2><p>Give Claude Code or Codex a clear picture of your workspace. Let it inspect worktrees, run your configured setup, and manage services, using the repositories and permissions you choose.</p><div class="mcp-actions"><a class="button button-primary" href="canopod-mcp.html">Explore Canopod MCP</a><a class="text-link" href="mcp.html">Connection guide</a></div><p class="mcp-compatibility">Claude Code · Codex · Compatible local MCP clients</p></div><div class="mcp-network" aria-label="Coding agents connect to your local Canopod backend through MCP"><div class="network-clients"><span>${icon('terminal')} Claude Code</span><span>${icon('code')} Codex</span></div><div class="network-wire" aria-hidden="true"></div><div class="network-hub">${mark}<div><strong>Canopod MCP</strong><span>One view of your local workspace</span></div><span class="protocol-badge">LOCAL</span></div><div class="network-permissions"><span>${icon('check')} Selected repositories</span><span>${icon('check')} Explicit permissions</span></div><div class="network-wire" aria-hidden="true"></div><div class="network-resources"><span>${icon('branch')} Worktrees</span><span>${icon('terminal')} Services</span><span>${icon('layers')} Setup jobs</span></div><p>Connect locally. Share access deliberately.</p></div></div></section>`;
}

export function workflowLinks() {
  return `<section class="use-cases-section container"><div class="section-heading split-heading"><div><p class="eyebrow">BUILT FOR THE WORK BETWEEN COMMITS</p><h2>Your day rarely stays<br>on one branch.</h2></div><a class="text-link" href="workflows.html">Find your workflow</a></div><div class="use-case-grid"><a href="workflows.html#review"><span class="use-case-label">PR REVIEWS</span><h3>Try the change.<br>Keep your work open.</h3><p>Run a review branch alongside your current feature, with its own services and ports.</p><span class="text-link">Review without the shuffle</span></a><a href="workflows.html#hotfix"><span class="use-case-label">HOTFIXES</span><h3>Handle the urgent bit.<br>Then come right back.</h3><p>Give the fix a separate worktree and leave your unfinished feature where it is.</p><span class="text-link">Make room for a hotfix</span></a><a href="workflows.html#agents"><span class="use-case-label">CODING AGENTS</span><h3>Give each task<br>a place to work.</h3><p>Keep agent sessions with the branch, runtime context, and services they belong to.</p><span class="text-link">Work alongside your agents</span></a></div></section>`;
}
